import re
from typing import List, Dict, Any
from datetime import timedelta

class AIAnalyzer:
    AI_KEYWORDS = [
        "copilot", "gpt", "llm", "ai-generated", "refactored by ai",
        "chatgpt", "openai", "claude", "generated by"
    ]

    def __init__(self):
        pass

    def analyze_commit(self, metadata: Dict[str, Any], diffs: List[Dict[str, Any]]) -> float:
        """
        Calculate a probability score (0.0 to 1.0) that a commit is AI-generated.
        """
        score = 0.0
        
        # 1. Message Analysis
        message = metadata["message"].lower()
        if any(keyword in message for keyword in self.AI_KEYWORDS):
            score += 0.5
            
        # 2. Velocity Analysis (Simple Hunk Size vs Effort)
        # Humans usually don't write hundreds of lines of perfect code in one burst
        # unless it's a copy-paste or a major refactor.
        stats = metadata["stats"]
        lines_changed = stats["lines"]
        if lines_changed > 200:
            score += 0.2
        elif lines_changed > 500:
            score += 0.4
            
        # 3. Code Structure (Heuristic: Lack of "human" comments or idiosyncrasies)
        # For now, we'll check for high density of boilerplate-like patterns
        for diff in diffs:
            if self._is_boilerplate_heavy(diff["diff_text"]):
                score += 0.1
                
        return min(score, 1.0)

    def _is_boilerplate_heavy(self, diff_text: str) -> bool:
        """Heuristic check for very clean, boilerplate-heavy code."""
        # Check for common AI patterns: perfect docstrings, no 'TODO's, etc.
        # This is a simplified placeholder for Phase 1.
        if "TODO" in diff_text or "FIXME" in diff_text:
            return False
        
        # AI often produces very consistent indentation and spacing
        # We can look for highly repetitive structures
        lines = diff_text.splitlines()
        if len(lines) > 20 and all(len(l.strip()) > 0 for l in lines if not l.startswith(("+", "-"))):
            return True
            
        return False

    def generate_heatmap(self, commit_scores: List[Dict[str, Any]]) -> Dict[str, float]:
        """Aggregate scores by file path."""
        heatmap = {}
        for entry in commit_scores:
            score = entry["score"]
            for diff in entry["diffs"]:
                path = diff["file_path"]
                if path not in heatmap:
                    heatmap[path] = []
                heatmap[path].append(score)
        
        # Average the scores for each file
        return {path: sum(scores) / len(scores) for path, scores in heatmap.items()}
